name: Pull Request

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  # Job 1: Сборка проекта
  build:
    runs-on: ubuntu-22.04

    steps:
      # Шаг 1: Выполняем checkout кода
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Установка прав на выполнение для gradlew
      - name: Set executable permissions for gradlew
        run: chmod +x ./gradlew

      # Шаг 3: Настройка JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'

      # Шаг 4: Кэширование зависимостей Gradle
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Шаг 5: Сборка проекта с помощью Gradle
      - name: Build project with Gradle
        run: ./gradlew build --no-daemon

  # Job 2: Запуск unit-тестов
  test:
    needs: build # Этот job выполняется после успешного завершения job "build"
    runs-on: ubuntu-22.04

    steps:
      # Шаг 1: Выполняем checkout кода
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Установка прав на выполнение для gradlew
      - name: Set executable permissions for gradlew
        run: chmod +x ./gradlew

      # Шаг 3: Настройка JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'

      # Шаг 4: Запуск unit-тестов
      - name: Run unit tests
        run: ./gradlew test --no-daemon

      # Шаг 5: Генерация отчета о покрытии кода тестами
      - name: Generate coverage report
        run: ./gradlew jacocoTestReport

      # Шаг 6: Публикация отчета о покрытии в GitHub Artifacts
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: build/jacoco/